name: test
on:
  push:
    branches: [main]

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./
        id: modify-json
        with:
          __inputFile: ./test.json
          __outputFile: ./output.json
          api_key: "key"
          client_id: "2313123"
          client_secret: "32131mdqpm"
          sensor_data: "big string"
          service_account__account_name: test
          service_account__password: password
          service_account__different__nested: nested
